# See more information at: https://www.mcbbs.net/forum.php?mod=viewthread&tid=1007749
replace: true
mask: 爱你
add:
- 阿伟死了
remove:
- fxxx
Msg_Reject: '&b[BWK]&a莫生气！莫生气！有什么事都好解决的，不要发晦气的话哦'
Msg_Reload: '&b[BWK]&a配置文件已重载'
Msg_test: '&3[&7!&3]&e 敏感句测试已开启，输入&ccancel&e取消测试'
Msg_NoPerm: '&b[BWK]&c执行失败，尚未找到相关权限'
Msg_maskChange: '&b[BWK]&a掩码替换成功!'
